Src/Inspinia_MVC5/Controllers/MonedasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebCartera.Models;
using EntityState = System.Data.Entity.EntityState;

namespace WebCartera.Controllers
{
    public class MonedasController : Controller
    {
        private readonly CarteraEntities db = new CarteraEntities();
        private readonly seguridadrolmodulo permiso = Parametro.VerificaPermiso("USE");
        private Parametro sesion = Parametro.ObtenerSesionPagina();


        // GET: Monedas
        public ActionResult Index()
        {
            
            var tmonedas = db.tmonedas.Where(m => m.Id_Usuario == sesion.Usuario.Id);
            return View(tmonedas.ToList());
        }
 
        // GET: Monedas/Create
        public ActionResult Create()
        {
            //Precargo valores necesario para crear una categoria            
            tmoneda moneda = new tmoneda();
            moneda.Id_Usuario = sesion.Usuario.Id;
            moneda.Activo = true;        
            return View(moneda);                        
        }

        // POST: Monedas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Id_Usuario,Descripcion,Simbolo,Activo")] tmoneda tmoneda)
        {
            if (ModelState.IsValid)
            {
                db.tmonedas.Add(tmoneda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }            
            return View(tmoneda);
        }

        // GET: Monedas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tmoneda tmoneda = db.tmonedas.Find(id);
            if (tmoneda == null)
            {
                return HttpNotFound();
            }            
            return View(tmoneda);
        }

        // POST: Monedas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Id_Usuario,Descripcion,Simbolo,Activo")] tmoneda tmoneda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tmoneda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }            
            return View(tmoneda);
        }

        // GET: Monedas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tmoneda tmoneda = db.tmonedas.Find(id);
            if (tmoneda == null)
            {
                return HttpNotFound();
            }
            return View(tmoneda);
        }

        // POST: Monedas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            tmoneda moneda = db.tmonedas.Find(id);

            int Movimientos = moneda.tcuentas.Count;

            if (Movimientos > 0)
            {
                moneda.Activo = false;
                db.Entry(moneda).State = EntityState.Modified;
            }
            else
            {
                db.tmonedas.Remove(moneda);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Src/Inspinia_MVC5/Views/Monedas/Create.cshtml
@model WebCartera.Models.tmoneda

@{
    ViewBag.Title = "Crear Moneda";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Categorias</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Index", "Inicio")">Inicio</a>
            </li>
            <li class="active breadcrumb-item">
                <a href="@Url.Action("Index", "Monedas")">Monedas</a>
            </li>
            <li class="active breadcrumb-item">
                <strong>Crear</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-content text-left p-md">
                    <h2>
                        <span class="text-navy">Crear Moneda</span>

                    </h2>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationMessage("ModelErr", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id_Usuario)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Simbolo, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Simbolo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Simbolo, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <div class="checkbox">
                                        @Html.EditorFor(model => model.Activo)
                                        @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input class="btn btn-primary" type="submit" value="Guardar" />
                                    <button class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Monedas")';return false;">Cancelar</button>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{    
    @Scripts.Render("~/bundles/jqueryForm")
}

Src/Inspinia_MVC5/Views/Monedas/Delete.cshtml
@model WebCartera.Models.tmoneda

@{
    ViewBag.Title = "Delete";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Categorias</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Index", "Inicio")">Inicio</a>
            </li>
            <li class="active breadcrumb-item">
                <a href="@Url.Action("Index", "Monedas")">Monedas</a>
            </li>
            <li class="active breadcrumb-item">
                <strong>Eliminar</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-content text-left p-md">
                    <h2>
                        <span class="text-navy">Esta seguro de eliminar esta moneda ?</span>

                    </h2>                    
                    <div>

                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Descripcion)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Descripcion)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Simbolo)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Simbolo)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Activo)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Activo)
                            </dd>

                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input class="btn btn-danger" type="submit" value="Borrar" />
                                    <button class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Monedas")';return false;">Cancelar</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Src/Inspinia_MVC5/Views/Monedas/Details.cshtml
@model WebCartera.Models.tmoneda

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>tmoneda</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Simbolo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Simbolo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.seguridadusuario.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.seguridadusuario.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Src/Inspinia_MVC5/Views/Monedas/Edit.cshtml
@model WebCartera.Models.tmoneda

@{
    ViewBag.Title = "Editar Moneda";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Categorias</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Index", "Inicio")">Inicio</a>
            </li>
            <li class="active breadcrumb-item">
                <a href="@Url.Action("Index", "Monedas")">Monedas</a>
            </li>
            <li class="active breadcrumb-item">
                <strong>Editar</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-content text-left p-md">
                    <h2>
                        <span class="text-navy">Editar Moneda</span>

                    </h2>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationMessage("ModelErr", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id_Usuario)
                            @Html.HiddenFor(model => model.Id)
                            <div class="form-group">
                                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Simbolo, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Simbolo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Simbolo, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">                               
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10 text-left">
                                        @Html.EditorFor(model => model.Activo, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input class="btn btn-primary" type="submit" value="Guardar" />
                                    <button class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Monedas")';return false;">Cancelar</button>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/bundles/jqueryForm")
}

Src/Inspinia_MVC5/Views/Monedas/Index.cshtml
@using WebCartera.Helpers
@model IEnumerable<WebCartera.Models.tmoneda>

@{
    ViewBag.Title = "Mantenimiento de Monedas";
}
<div id="replacetarget">
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Monedas</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="@Url.Action("Index", "Inicio")">Inicio</a>
                </li>
                <li class="active breadcrumb-item">
                    <strong>Monedas</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
<div class="wrapper wrapper-content ">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h4>Listado de Monedas </h4>
                </div>
                <div class="ibox-content p-md">
                    <p>
                        <div class="row">
                            <div class="col-sm-6 col-lg-4">
                                <div class="input-group">
                                    <input type="search" id="search" class="form-control dynatable-search" placeholder="Buscar .."><span class="btn btn-primary fa fa-search"></span>
                                </div>
                            </div>

                            <div class="col-sm-2 col-lg-4">

                            </div>
                            <div class="col-sm-4 col-lg-4">
                                <select class="form-control" id="search-estado" name="estado">
                                    <option>-- Todos --</option>
                                    <option>Activo</option>
                                    <option>Inactivo</option>
                                </select>
                            </div>


                        </div>
                    </p>
                    <div class="table-responsive">
                        <table id="t_datos" class="table table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Descripcion)
                                    </th>
                                    <th data-hide="phone">
                                        @Html.DisplayNameFor(model => model.Simbolo)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Activo)
                                    </th>
                                    <th data-dynatable-no-sort="true">
                                        @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-plus'></span>", "Nuevo", "Create", "Monedas", htmlAttributes: new { @class = "btn btn-secondary pull-right" })
                                    </th>
                                </tr>
                            </thead>
                            <tbody class="animated d-none">
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Descripcion)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Simbolo)
                                        </td>
                                        <td class="text-center">@(item.Activo ? "Activo" : "Inactivo")</td>
                                        <td>
                                            <div class="pull-right">
                                                @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-pencil'></span> ", "Editar", "Edit", "Monedas", routeValues: new { id = item.Id }, htmlAttributes: new { data_modal = "", @class = "btn btn-outline-secondary btn-sm" })
                                                @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-trash'></span>", "Eliminar", "Delete", "Monedas", routeValues: new { id = item.Id }, htmlAttributes: new { data_modal = "", @class = "btn btn-outline-secondary btn-sm" })
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
  </div>

    @section Styles {
        @Styles.Render("~/plugins/dynatableStyles")
    }
    @section Scripts {
        @Scripts.Render("~/plugins/dynatable")
        <script type="text/javascript">
            var dynatable = $('#t_datos').dynatable({
                features: {
                    perPageSelect: false,
                    search: false,
                    recordCount: false
                },
                dataset: {
                    perPageDefault: 5,
                    perPageOptions: [5, 10, 15, 20],
                },
                inputs: {
                    paginationPrev: '<span class="fa fa-arrow-left"></span>',
                    paginationNext: '<span class="fa fa-arrow-right"></span>',
                    recordCountText: 'De ',
                    processingText: 'Prosesando...',
                    queries: $('#search')
                }

            }).data('dynatable');
            $('#search-estado').change(function () {
                var value = $(this).val();
                if (value === "-- Todos --") {
                    dynatable.queries.remove("estado");
                } else {
                    dynatable.queries.add("estado", value);
                }
                dynatable.process();
            });
            $(function () {
                $("#search-estado").val("Activo").change();
                $(".animated").removeClass("d-none");
                $(".animated").addClass("fadeIn");
            });
        </script>
    }