Src/Inspinia_MVC5/Controllers/CuentasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using WebCartera.Models;

using EntityState = System.Data.Entity.EntityState;
using WebCartera.OptionEnums;
using System.Reflection;
using System.ComponentModel;
using WebCartera.Helpers.OptionEnums;
using System.Data.Entity;
using System.Data.Entity.Validation;

namespace WebCartera.Controllers
{
    public class CuentasController : Controller
    {
        private readonly CarteraEntities db = new CarteraEntities();      
        private readonly seguridadrolmodulo permiso = Parametro.VerificaPermiso("USE");
        private Parametro sesion = Parametro.ObtenerSesionPagina();

        // GET: Cuentas
        public ActionResult Index()
        {
            try
            {              
                List<tcuenta> cuentas = db.tcuentas.Where(m => m.Id_Usuario == sesion.Usuario.Id).ToList();
                ViewBag.Id_Moneda = new SelectList(db.tmonedas.Where(m => m.Id_Usuario == sesion.Usuario.Id && m.Activo), "Id", "Descripcion");
                return View(cuentas);
            }
            catch {
                AddMsgWeb("Error al acceder a los datos", ToastType.Error);
                return RedirectToAction("Index","Inicio");
            }
        }

        // GET: Cuentas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tcuenta tcuenta = db.tcuentas.Find(id);
            if (tcuenta == null)
            {
                return HttpNotFound();
            }
            return View(tcuenta);
        }

        // GET: Cuentas/Create
        public ActionResult Create()
        {            
            tcuenta cuenta = new tcuenta();
            cuenta.Id_Usuario = sesion.Usuario.Id;
            cuenta.Activo = true;
            ViewBag.Id_Moneda = new SelectList(db.tmonedas.Where(m=> m.Id_Usuario == sesion.Usuario.Id && m.Activo), "Id", "Descripcion");
            ViewBag.Id_TipoCuenta = new SelectList(sesion.TipoCuentas, "Id", "Descripcion");
            return View(cuenta);
        }

        // POST: Cuentas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_Usuario,Id_Moneda,Nombre,Descripcion,Imagen,SaldoActual,Activo,Id_TipoCuenta")] tcuenta pCuenta)
        {           
            if (ModelState.IsValid)
            {
                try
                {
                    pCuenta.CuentaCredito = Convert.ToBoolean( pCuenta.Id_TipoCuenta);
                   db.tcuentas.Add(pCuenta);
                    db.SaveChanges();
                    //Se actuliza la session del usuario con las nuevas cuentas
                    ActualizaCuenta(-1);
                    AddMsgWeb("Registro agregado exitosamente", ToastType.Success);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("ModelErr", ex.Message);
                    AddMsgWeb("Error al agregar el registro",ToastType.Error);                    
                }
            }                        
            ViewBag.Id_Moneda = new SelectList(db.tmonedas.Where(m => m.Id_Usuario == sesion.Usuario.Id && m.Activo), "Id", "Descripcion", pCuenta.Id_Moneda);
            ViewBag.Id_TipoCuenta = new SelectList(sesion.TipoCuentas, "Id", "Descripcion", pCuenta.TipoCuentas);
            return View(pCuenta);
        }

        // GET: Cuentas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tcuenta cuenta = db.tcuentas.Find(id);
            if (cuenta == null)
            {
                return HttpNotFound();
            }
            cuenta.Id_TipoCuenta = Convert.ToInt16(cuenta.CuentaCredito);
            ViewBag.Id_Moneda = new SelectList(db.tmonedas.Where(m => m.Id_Usuario == sesion.Usuario.Id && m.Activo), "Id", "Descripcion",cuenta.Id_Moneda);
            ViewBag.Id_TipoCuenta = new SelectList(sesion.TipoCuentas, "Id", "Descripcion", cuenta.Id_TipoCuenta);
            return View(cuenta);
        }

        // POST: Cuentas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Id_Usuario,Id_Moneda,Nombre,Descripcion,Imagen,SaldoActual,Activo,Id_TipoCuenta")] tcuenta pCuenta)
        {
            
            if (ModelState.IsValid)
            {
                try {
                    pCuenta.CuentaCredito = Convert.ToBoolean(pCuenta.Id_TipoCuenta);
                    db.tcuentas.Add(pCuenta);
                    db.Entry(pCuenta).State = EntityState.Modified;
                    db.SaveChanges();
                    ActualizaCuenta(pCuenta.Id);
                    AddMsgWeb("Registro editado exitosamente", ToastType.Success);                    
                    return RedirectToAction("Index");
                }
                catch (Exception ex) {
                    ModelState.AddModelError("ModelErr", ex.Message);
                    AddMsgWeb("Error al editar el registro",ToastType.Error);                    
                }              
            }
            ViewBag.Id_Moneda = new SelectList(db.tmonedas.Where(m => m.Id_Usuario == sesion.Usuario.Id && m.Activo), "Id", "Descripcion",pCuenta.Id_Moneda);
            ViewBag.Id_TipoCuenta = new SelectList(sesion.TipoCuentas, "Id", "Descripcion", pCuenta.Id_TipoCuenta);
            return View(pCuenta);
        }

        // GET: Cuentas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tcuenta tcuenta = db.tcuentas.Find(id);
            if (tcuenta == null)
            {
                return HttpNotFound();
            }
            tcuenta.TipoCuentas = sesion.TipoCuentas.Find(c=> c.Id== ((tcuenta.CuentaCredito == true) ? 1 : 0));
            return View(tcuenta);
        }

        // POST: Cuentas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tcuenta Cuenta = db.tcuentas.Find(id);
            int Movimientos = Cuenta.tmovimientoes.Count;
            Cuenta.TipoCuentas = sesion.TipoCuentas.Find(c => c.Id == ((Cuenta.CuentaCredito == true) ? 1 : 0));
            try
            {
            
                if (Movimientos > 0)
                {
                    Cuenta.Activo = false;
                    db.Entry(Cuenta).State = EntityState.Modified;
                    AddMsgWeb("Registro desactivo, cuenta con movimientos asociados", ToastType.Warning);                  
                }
                else
                {
                    db.tcuentas.Remove(Cuenta);
                    AddMsgWeb("Registro eliminado exitosamente",ToastType.Success);                
                }           
                db.SaveChanges();
                ActualizaCuenta(Cuenta.Id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("ModelErr", ex.Message);
                AddMsgWeb("Error al eliminar el registro",ToastType.Error);            
                tcuenta tcuenta = db.tcuentas.Find(id);               
                return View(tcuenta);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public void ActualizaCuenta(int? IdCuenta)
        {
            sesion.Cuentas = db.tcuentas.Where(c => c.Id_Usuario == sesion.Usuario.Id && c.Activo).ToList();
            if (IdCuenta == sesion.CuentaFiltro)
            {
                sesion.CuentaFiltro = 0;
            }
        }

        // GET: Cuentas/Ingreso
        public ActionResult Ingreso()
        {
            int tipo = IntValue(TipoMovimiento.Credito);
            tmovimiento ingreso = new tmovimiento();
            ingreso.Id_Usuario = sesion.Usuario.Id;
            ingreso.TipoMovimiento = TipoMovimiento.Credito;      
            ingreso.Fecha = DateTime.Now;
            ViewBag.Id_Cuenta = new SelectList(sesion.Cuentas, "Id", "Nombre", sesion.CuentaFiltro);
            ViewBag.Id_Categoria = new SelectList(
                db.tcategorias.Where(c => c.IdUsuario == sesion.Usuario.Id && c.Tipo == tipo && c.Activo),
                "Id",
                "Nombre");
            return View(ingreso);
        }
        // POST: Cuentas/Ingreso
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Ingreso([Bind(Include = "Id_Usuario,Id_Categoria,Id_Cuenta,Fecha,Descripcion,TipoMovimiento,Monto")] tmovimiento pMovimiento)
        {
            if (pMovimiento.Monto < 0)
            {
                AddMsgWeb("Monto invalido, valor negativo", ToastType.Error);
                ModelState.AddModelError("ModelErr", "Monto invalido, valor negativo");
            }
            if (ModelState.IsValid)

Src/Inspinia_MVC5/Views/Cuentas/Create.cshtml
@model WebCartera.Models.tcuenta
@{
    ViewBag.Title = "Crear Cuenta";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Cuentas</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Index", "Inicio")">Inicio</a>
            </li>
            <li class="active breadcrumb-item">
                <a href="@Url.Action("Index", "Cuentas")">Cuentas</a>
            </li>
            <li class="active breadcrumb-item">
                <strong>Crear</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-content text-left">
                    <h2>
                        <span class="text-navy">Crear Cuenta</span>

                    </h2>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationMessage("ModelErr", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id_Usuario)
                        @Html.HiddenFor(model => model.Activo)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group picker">
                            @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="input-group">
                                    @Html.EditorFor(model => model.Imagen, new { htmlAttributes = new { @class = "form-control inputpicker", autocomplete = "off" } })
                                    <span id="ImgIcosm" class="btn btn-outline-secondary fa fa-ban"></span>
                                </div>
                                @Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.tmoneda.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Id_Moneda", null, "-- Moneda--", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Id_Moneda, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.TipoCuentas, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Id_TipoCuenta", null, "-- Tipo Cuenta--", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Id_TipoCuenta, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.SaldoActual, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.SaldoActual, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                                @Html.ValidationMessageFor(model => model.SaldoActual, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input class="btn btn-primary" type="submit" value="Guardar" />
                                <button class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Cuentas")';return false;">Cancelar</button>
                            </div>
                        </div>
                    </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    @Styles.Render("~/Scripts/plugins/iconpicker/css/icos.css")
}
@section scripts{
    @Scripts.Render("~/Scripts/plugins/iconpicker/icos.js")
    @Scripts.Render("~/bundles/jqueryForm")
}

Src/Inspinia_MVC5/Views/Cuentas/Delete.cshtml
@model WebCartera.Models.tcuenta

@{
    ViewBag.Title = "Borrar Cuenta";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Categorias</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Index", "Inicio")">Inicio</a>
            </li>
            <li class="active breadcrumb-item">
                <a href="@Url.Action("Index", "Cuentas")">Cuentas</a>
            </li>
            <li class="active breadcrumb-item">
                <strong>Borrar</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content">
    <div class="ibox ">
        <div class="ibox-content">
            <div class="row">
                <div class="col-sm-6 b-r">
                    <h3 class="m-t-none m-b">Cuenta</h3>
                    <p>Esta seguro de eliminar este elemento?</p>
                    <div class="form-group ">
                        @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2 font-bold" })
                        <div class="col-md-10">
                            <i class="fa @Model.Imagen fa-2x"></i>
                        </div>
                    </div>
                    <div class="form-group ">
                        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2 font-bold" })
                        <div class="col-md-10">
                            <div class="bg-muted form-control">
                                @Html.DisplayFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control " } })
                            </div>
                        </div>
                    </div>
                    <div class="form-group ">
                        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2 font-bold" })
                        <div class="col-md-10">
                            <div class="bg-muted form-control">
                                @Html.DisplayFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control " } })
                            </div>
                        </div>
                    </div>
                    <div class="form-group ">
                        @Html.LabelFor(model => model.SaldoActual, htmlAttributes: new { @class = "control-label col-md-2 font-bold" })
                        <div class="col-md-10">
                            <div class="bg-muted form-control">
                                @Model.tmoneda.Simbolo
                                @Html.DisplayFor(model => model.SaldoActual_Format, new { htmlAttributes = new { @class = "form-control " } })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2 font-bold" })
                        <div class="col-md-10">
                            <div class="bg-muted form-control">
                                @(Model.Activo ? "Activo" : "Inactivo")
                            </div>
                        </div>
                    </div>


                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input class="btn btn-danger" type="submit" value="Borrar" />
                                <button class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Cuentas")';return false;">Cancelar</button>
                            </div>
                        </div>
                    }
                </div>
                <div class="d-none d-sm-block col-sm-6">
                    <h4 class="text-center text-primary">Icono</h4>
                    <p class="text-center align-self-center">
                        <i class="fa @Model.Imagen big-icon "></i>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

Src/Inspinia_MVC5/Views/Cuentas/Details.cshtml
@model WebCartera.Models.tcuenta

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>tcuenta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SaldoActual)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SaldoActual)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SaldoAnterior)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SaldoAnterior)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.seguridadusuario.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.seguridadusuario.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tmoneda.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tmoneda.Descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Src/Inspinia_MVC5/Views/Cuentas/Edit.cshtml
@model WebCartera.Models.tcuenta

@{
    ViewBag.Title = "Editar Cuenta";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Categorias</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Index", "Inicio")">Inicio</a>
            </li>
            <li class="active breadcrumb-item">
                <a href="@Url.Action("Index", "Cuentas")">Cuentas</a>
            </li>
            <li class="active breadcrumb-item">
                <strong>Editar</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-content text-left p-md">
                    <h2>
                        <span class="text-navy">Editar Cuenta</span>

                    </h2>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationMessage("ModelErr", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id_Usuario)
                        @Html.HiddenFor(model => model.Id)
                        @Html.HiddenFor(model => model.SaldoActual)
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group picker">
                            @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="input-group">
                                    @Html.EditorFor(model => model.Imagen, new { htmlAttributes = new { @class = "form-control inputpicker", autocomplete = "off" } })
                                    <span id="ImgIcosm" class="btn btn-outline-secondary fa @Model.Imagen"></span>
                                </div>
                                @Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.tmoneda.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Id_Moneda", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Id_Moneda, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Id_TipoCuenta, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Id_TipoCuenta", null, "-- Tipo Cuenta--", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Id_TipoCuenta, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10 text-left">
                                @Html.EditorFor(model => model.Activo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input class="btn btn-primary" type="submit" value="Guardar" />
                                <button class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "Cuentas")';return false;">Cancelar</button>
                            </div>
                        </div>
                    </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    @Styles.Render("~/Scripts/plugins/iconpicker/css/icos.css")
}
@section scripts{
    @Scripts.Render("~/Scripts/plugins/iconpicker/icos.js")
    @Scripts.Render("~/bundles/jqueryForm")
}

Src/Inspinia_MVC5/Views/Cuentas/View.cshtml
@model WebCartera.Models.tmovimiento

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tmovimiento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Cuenta, "Id_Cuenta", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_Cuenta", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_Cuenta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Categoria, "Id_Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_Categoria", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Usuario, "Id_Usuario", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_Usuario", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_Usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Monto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Monto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Monto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>